// <auto-generated />
using System;
using FormatVnShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormatVnShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260130035705_AddCustomerAuthAndPasswords")]
    partial class AddCustomerAuthAndPasswords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FormatVnShop.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 30, 10, 57, 3, 947, DateTimeKind.Local).AddTicks(5705),
                            Email = "admin@format.vn",
                            IsActive = true,
                            PasswordHash = "$2a$11$mUCBGunH9.sVJM.h7y1cYeZEfIpzWgxskla/FfgzEczm.nQZ.VV8O",
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3397),
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 30, 10, 57, 4, 125, DateTimeKind.Local).AddTicks(1873),
                            Email = "manager@format.vn",
                            IsActive = true,
                            PasswordHash = "$2a$11$v04RUdep3blqRTR08Yk4P.uDOEbFwsoRQXitDCfH.C8Pmftj.uixK",
                            Role = 1,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 947, DateTimeKind.Local).AddTicks(5747),
                            Username = "manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 30, 10, 57, 4, 302, DateTimeKind.Local).AddTicks(3599),
                            Email = "staff@format.vn",
                            IsActive = true,
                            PasswordHash = "$2a$11$kDwubXcjJh6RDmvzISvvq.BmCceogwVeeJ3iOvp4XOD4e7AQVtBWe",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 4, 125, DateTimeKind.Local).AddTicks(1917),
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("FormatVnShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(5897),
                            Description = "Thời trang nữ",
                            ImageUrl = "/images/categories/nu.jpg",
                            Name = "NỮ",
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(5917)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(5925),
                            Description = "Thời trang nam",
                            ImageUrl = "/images/categories/nam.jpg",
                            Name = "NAM",
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(5927)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(5931),
                            Description = "Phụ kiện thời trang",
                            ImageUrl = "/images/categories/phukien.jpg",
                            Name = "PHỤ KIỆN",
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(5933)
                        });
                });

            modelBuilder.Entity("FormatVnShop.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Nguyễn Huệ, Q1, TP.HCM",
                            CreatedAt = new DateTime(2025, 7, 30, 10, 57, 3, 81, DateTimeKind.Local).AddTicks(9915),
                            Email = "nguyenvanan@gmail.com",
                            Name = "Nguyễn Văn An",
                            PasswordHash = "$2a$11$.thRG2RH1w84x3cWbE6da../w2redeNbo6bVdfu3OpBXskF0xAhla",
                            Phone = "0901234567",
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6391)
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Lê Lợi, Q3, TP.HCM",
                            CreatedAt = new DateTime(2025, 9, 30, 10, 57, 3, 262, DateTimeKind.Local).AddTicks(7330),
                            Email = "tranthibinh@gmail.com",
                            Name = "Trần Thị Bình",
                            PasswordHash = "$2a$11$U45UdTmZbOlzf/M.cd2nYugYNrivs4yyQCMzgcWI1VUyykpQonyjG",
                            Phone = "0912345678",
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 82, DateTimeKind.Local).AddTicks(114)
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Trần Hưng Đạo, Q5, TP.HCM",
                            CreatedAt = new DateTime(2025, 10, 30, 10, 57, 3, 438, DateTimeKind.Local).AddTicks(1691),
                            Email = "leminhcuong@gmail.com",
                            Name = "Lê Minh Cường",
                            PasswordHash = "$2a$11$J0O8T3NM1MMDRG5C7CloAekVrKAzwiH3FMVTMqqUQPXSy.T0Mavti",
                            Phone = "0923456789",
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 262, DateTimeKind.Local).AddTicks(7473)
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Võ Văn Tần, Q10, TP.HCM",
                            CreatedAt = new DateTime(2025, 11, 30, 10, 57, 3, 604, DateTimeKind.Local).AddTicks(8580),
                            Email = "phamthudung@gmail.com",
                            Name = "Phạm Thu Dung",
                            PasswordHash = "$2a$11$Vt/WsirFItPn5RBOS9Y.SuYO1LW.ZD/ourbVqcYUzWFM39hl4JGOW",
                            Phone = "0934567890",
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 438, DateTimeKind.Local).AddTicks(1748)
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Hai Bà Trưng, Q1, Hà Nội",
                            CreatedAt = new DateTime(2025, 12, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(1650),
                            Email = "hoangquocviet@gmail.com",
                            Name = "Hoàng Quốc Việt",
                            PasswordHash = "$2a$11$VNU1URZOkWJqpkzvKR8BPuHDhmpb2j4B1DAwFeQyuekYwVHYg1ur6",
                            Phone = "0945678901",
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 604, DateTimeKind.Local).AddTicks(8629)
                        });
                });

            modelBuilder.Entity("FormatVnShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2808),
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 12, 31, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2815),
                            OrderNumber = "ORD-2026-0001",
                            ShippingAddress = "123 Nguyễn Huệ, Q1, TP.HCM",
                            Status = "Delivered",
                            TotalAmount = 3117000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2813)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2836),
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 1, 10, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2837),
                            OrderNumber = "ORD-2026-0002",
                            ShippingAddress = "456 Lê Lợi, Q3, TP.HCM",
                            Status = "Delivered",
                            TotalAmount = 2580000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2836)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2842),
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 1, 15, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2845),
                            OrderNumber = "ORD-2026-0003",
                            ShippingAddress = "789 Trần Hưng Đạo, Q5, TP.HCM",
                            Status = "Shipped",
                            TotalAmount = 1827000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2844)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2846),
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 1, 20, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2849),
                            OrderNumber = "ORD-2026-0004",
                            ShippingAddress = "321 Võ Văn Tần, Q10, TP.HCM",
                            Status = "Processing",
                            TotalAmount = 4320000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2848)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2851),
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 1, 25, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2852),
                            OrderNumber = "ORD-2026-0005",
                            ShippingAddress = "654 Hai Bà Trưng, Q1, Hà Nội",
                            Status = "Pending",
                            TotalAmount = 1014000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2851)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2854),
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 1, 28, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2859),
                            OrderNumber = "ORD-2026-0006",
                            ShippingAddress = "123 Nguyễn Huệ, Q1, TP.HCM",
                            Status = "Pending",
                            TotalAmount = 1590000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(2858)
                        });
                });

            modelBuilder.Entity("FormatVnShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3277),
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 1827000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3279)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3284),
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 1290000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3285)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3295),
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 2,
                            UnitPrice = 1290000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3295)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3298),
                            OrderId = 3,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 1827000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3298)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3300),
                            OrderId = 4,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 3570000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3301)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3303),
                            OrderId = 4,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 750000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3304)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3306),
                            OrderId = 5,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 1014000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3306)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3308),
                            OrderId = 6,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 1590000m,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 3, 774, DateTimeKind.Local).AddTicks(3309)
                        });
                });

            modelBuilder.Entity("FormatVnShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6154),
                            Description = "Masterpiece by FORMAT. Kỹ thuật khâu tay thủ công tỉ mỉ, chất liệu dạ ấm áp (80% wool). Dáng suông dài, cổ hai ve.",
                            ImageUrl = "https://format.vn/media/catalog/product/1/0/10000752.jpg",
                            IsFeatured = true,
                            Name = "Áo măng tô dạ khâu tay dây lưng rời",
                            Price = 1827000m,
                            Stock = 15,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6130)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6163),
                            Description = "Quần ống suông chất liệu dạ cao cấp, đi kèm dây lưng rời. Phong cách lịch lãm cho phái nữ.",
                            ImageUrl = "https://format.vn/media/catalog/product/1/0/10005601.jpg",
                            IsFeatured = true,
                            Name = "Quần ống suông dạ dây lưng rời",
                            Price = 1290000m,
                            Stock = 25,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6160)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6171),
                            Description = "Thiết kế 2 lớp dày dặn, không cổ trẻ trung. Chất liệu dạ mịn, giữ ấm tốt.",
                            ImageUrl = "https://format.vn/media/catalog/product/1/0/10005588.jpg",
                            IsFeatured = false,
                            Name = "Áo Gile dạ 2 lớp không cổ",
                            Price = 1290000m,
                            Stock = 30,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6168)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6179),
                            Description = "Chân váy dạ 2 lớp, thiết kế cạp chun thoải mái, lịch sự cho công sở.",
                            ImageUrl = "https://format.vn/media/catalog/product/1/0/10005515.jpg",
                            IsFeatured = true,
                            Name = "Chân váy dạ 2 lớp cạp liền chun",
                            Price = 1590000m,
                            Stock = 20,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6176)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6186),
                            Description = "Công nghệ không đường may hiện đại, chất liệu cotton cao cấp, thoáng khí và bền màu.",
                            ImageUrl = "https://format.vn/media/catalog/product/1/0/10005496.jpg",
                            IsFeatured = true,
                            Name = "Áo polo nam không đường may cổ đức",
                            Price = 1014000m,
                            Stock = 40,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6183)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6230),
                            Description = "Áo khoác nam thiết kế sang trọng, chất liệu cao cấp, giữ ấm hiệu quả cho mùa đông.",
                            ImageUrl = "https://format.vn/media/catalog/product/1/0/10005390.jpg",
                            IsFeatured = false,
                            Name = "Áo khoác tay dài nam",
                            Price = 3570000m,
                            Stock = 35,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6196)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6238),
                            Description = "Quần nỉ nam năng động, cạp chun có dây rút, phù hợp cho phong cách thể thao/dạo phố.",
                            ImageUrl = "https://format.vn/media/catalog/product/1/0/10004947.jpg",
                            IsFeatured = true,
                            Name = "Quần ống bó nỉ cạp chun luồn dây",
                            Price = 750000m,
                            Stock = 18,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6235)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6246),
                            Description = "Công nghệ giữ nhiệt WarmMax độc quyền, mỏng nhẹ, giữ ấm cơ thể tối ưu.",
                            ImageUrl = "https://format.vn/media/catalog/product/1/0/10000183.jpg",
                            IsFeatured = true,
                            Name = "Áo giữ nhiệt WarmMax Light cổ tròn",
                            Price = 245000m,
                            Stock = 12,
                            UpdatedAt = new DateTime(2026, 1, 30, 10, 57, 2, 916, DateTimeKind.Local).AddTicks(6243)
                        });
                });

            modelBuilder.Entity("FormatVnShop.Models.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2
                        });
                });

            modelBuilder.Entity("FormatVnShop.Models.Category", b =>
                {
                    b.HasOne("FormatVnShop.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FormatVnShop.Models.Order", b =>
                {
                    b.HasOne("FormatVnShop.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FormatVnShop.Models.OrderItem", b =>
                {
                    b.HasOne("FormatVnShop.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormatVnShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FormatVnShop.Models.ProductCategory", b =>
                {
                    b.HasOne("FormatVnShop.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormatVnShop.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FormatVnShop.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("FormatVnShop.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FormatVnShop.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FormatVnShop.Models.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
